[package]
name = "bittoko"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
dns-lookup = "1.0.8"
scroll = "0.10"
